models:
  - name: local_dummy
    type: local
    weight: 1.0
  - name: remote_api
    type: api
    weight: 1.0
router:
  max_candidates: 2
scoring:
  pass_threshold: 0.70
logging:
  audit_file: ./audit.log
