site_name: BLUX-cA
site_description: Enterprise Conscious Agent Core
nav:
  - Home: index.md
  - Vision: VISION.md
  - Architecture: ARCHITECTURE.md
  - Constitution: CONSTITUTION.md
  - Ethics Engine: ETHICS_ENGINE.md
  - Discernment: DISCERNMENT.md
  - Interventions: INTERVENTIONS.md
  - Integrations: INTEGRATIONS.md
  - Install: INSTALL.md
  - Operations: OPERATIONS.md
  - Security: SECURITY.md
  - Privacy: PRIVACY.md
  - Configuration: CONFIGURATION.md
  - Troubleshooting: TROUBLESHOOTING.md
  - Roadmap: ROADMAP.md
theme:
  name: material
  features:
    - content.code.copy
